services:
    rb_user.registration.form.type:
        class: RB\UserBundle\Form\RegistrationFormType
        tags:
            - { name: form.type, alias: rb_user_registration }

    rb_user_extension:
        class: RB\UserBundle\Twig\RBUserExtension
        arguments: ["@service_container", "@twig", "@session"]
        tags:
            - { name: twig.extension }
    # rb_user.profile.form.type:
    #     class: RB\UserBundle\Form\ProfileFormType
    #     tags:
    #         - { name: form.type, alias: rb_user_profile }

    # rb_user.twig.user_extension:
    #     class: RB\UserBundle\Twig\UserExtension
    #     arguments: [@service_container,@translator]
    #     tags:
    #         - { name: twig.extension }

    rb_user.services:
        class: RB\UserBundle\Services\RBUserService
        arguments: ["@service_container", "@session", "@router"]